name: build

on:
  push:
    branches-ignore:
      - gh-pages
jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - shell: bash
        run: pip install pyflakes coverage pytest
      - shell: bash
        run: |
          if [ ! -z "$REQ_PATH" ]; then
            pip install -r "$REQ_PATH";
          fi;
        env:
          REQ_PATH: ""

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: pyflakes .
